import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Anime Wildcard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="App grid grid-rows-layout min-h-svh">
            <Header/>
            {children}
            <Footer/>
        </div>
      </body>
    </html>
  );
}
